"""empty message

Revision ID: 8ced7e87b469
Revises: da0931adf147
Create Date: 2017-10-30 09:49:55.647953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ced7e87b469'
down_revision = 'da0931adf147'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('coupon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'coupon')
    # ### end Alembic commands ###


def upgrade_recipe():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_recipe():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

