"""empty message

Revision ID: da0931adf147
Revises: 4eece9597ce2
Create Date: 2017-10-26 12:57:29.243757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da0931adf147'
down_revision = '4eece9597ce2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_recipe():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_photos')
    op.add_column('steps', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'steps', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_recipe():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.drop_column('steps', 'photo_id')
    op.create_table('step_photos',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], [u'photos.id'], name=u'step_photos_ibfk_1'),
    sa.ForeignKeyConstraint(['step_id'], [u'steps.id'], name=u'step_photos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###

