"""empty message

Revision ID: fdf766ce5743
Revises: 
Create Date: 2017-07-26 10:52:43.271067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdf766ce5743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('check_num', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=2), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'category', sa.Column('notflase', sa.String(length=120), nullable=True))
    op.drop_column(u'category', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'category', sa.Column('note', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column(u'category', 'notflase')
    op.drop_table('finances')
    # ### end Alembic commands ###
